# Agent Configuration
# This file is loaded by the agent at startup.
# If this file is not found or is invalid, the agent will use built-in default values from config.go

protocol: "H1C" # Options: H1C, H1TLS, H2TLS, H3, WS, WSS
server_ip: "192.168.2.11"
server_port: "8888" # Ensure this matches the desired listener on the server

check_in_endpoint: "/"
results_endpoint: "/results"
websocket_endpoint: "/ws" # Used if protocol is WS or WSS

delay: "5s" # Duration string, e.g., 5s, 1m, 100ms
jitter: 0.20   # e.g., 0.20 for +/- 20%

beacon_mode: true # true for beacon, false for persistent (HTTP-only)
checkin_method: "GET"         # "GET" or "POST" (for HTTP types) - if padding is enabled HAS TO BE POST

enable_padding: true # if true, checkin_method has to be POST
min_padding_bytes: 64
max_padding_bytes: 1024

uuid: "agent_deadbeef01" # this will be replaced with generated UUID later, ignore actual value here

skip_verify_tls: true # true means ALLOW self-signed certs