// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ConnectWebSocket(arg1) {
  return window['go']['main']['App']['ConnectWebSocket'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DisconnectWebSocket() {
  return window['go']['main']['App']['DisconnectWebSocket']();
}

export function ExecuteAgentTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteAgentTask'](arg1, arg2, arg3);
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetServerMessages() {
  return window['go']['main']['App']['GetServerMessages']();
}

export function GetWebSocketStatus() {
  return window['go']['main']['App']['GetWebSocketStatus']();
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}

export function SendWebSocketMessage(arg1, arg2) {
  return window['go']['main']['App']['SendWebSocketMessage'](arg1, arg2);
}

export function UpdatePreferences(arg1) {
  return window['go']['main']['App']['UpdatePreferences'](arg1);
}
