// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';
import {models} from '../models';

export function Connect(arg1:string):Promise<frontend.ConnectionStatusDTO>;

export function Disconnect():Promise<frontend.ConnectionStatusDTO>;

export function GetAgents():Promise<Array<frontend.AgentDTO>>;

export function GetConnectionStatus():Promise<frontend.ConnectionStatusDTO>;

export function GetServerMessageModel():Promise<frontend.ServerMessageDTO>;

export function SendCommand(arg1:models.CommandRequest):Promise<frontend.CommandResponseDTO>;
