// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetServerMessageModel() {
  return window['go']['main']['App']['GetServerMessageModel']();
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}
