simulation_plan:
    - name: "Run Specific Command - Manual"
      action: "run_cmd"
      args:
        command_line: "whoami"

    - name: "Perform System Recon - Randomized (System)"
      action: "run_cmd"
      category: "system_recon"

    - name: "Perform Network Recon - Randomized (Network)"
      action: "run_cmd"
      category: "network_recon"

    - name: "Perform User Recon - Randomized (User)"
      action: "run_cmd"
      category: "user_recon"

    - name: "Perform General Discovery - Randomized (Discovery)"
      action: "run_cmd"
      category: "discovery"