// Code generated by cmd/build/main.go; DO NOT EDIT.
package main

import (
	"numinon_shadow/internal/agent/config"
	"time"
)

var embeddedAgentConfig = config.AgentConfig{
	Protocol:          config.AgentProtocol("H1TLS"),
	ServerIP:          "127.0.0.1",
	ServerPort:        "8888",
	CheckInEndpoint:   "/",
	ResultsEndpoint:   "/results",
	WebsocketEndpoint: "/ws",
	Delay:             time.Duration(10000000000),
	Jitter:            0.2,
	CheckinMethod:     "POST",
	EnablePadding:     true,
	MinPaddingBytes:   64,
	MaxPaddingBytes:   1024,
	BeaconMode:        true,
	UUID:              "d061e77c-d404-48f8-bb73-ef1f899833f5", // This will be the generated UUID pkg
	SkipVerifyTLS:     true,
}

// getEmbeddedAgentConfig is called by the agent's main.go to retrieve this configuration.
func getEmbeddedAgentConfig() config.AgentConfig {
	return embeddedAgentConfig
}
