// Code generated by cmd/build/main.go; DO NOT EDIT.
package main

import (
	"numinon_shadow/internal/agent/config"
	"time"
)

var embeddedAgentConfig = config.AgentConfig{
	Protocol:          config.AgentProtocol("WS"),
	ServerIP:          "192.168.2.249",
	ServerPort:        "8888",
	CheckInEndpoint:   "/",
	ResultsEndpoint:   "/results",
	WebsocketEndpoint: "/ws",
	Delay:             time.Duration(5000000000),
	Jitter:            0.2,
	CheckinMethod:     "GET",
	EnablePadding:     true,
	MinPaddingBytes:   64,
	MaxPaddingBytes:   1024,
	BeaconMode:        true,
	UUID:              "975154f2-99f0-4caa-8f73-0b31e06b2817", // This will be the generated UUID pkg
	SkipVerifyTLS:     true,
}

// getEmbeddedAgentConfig is called by the agent's main.go to retrieve this configuration.
func getEmbeddedAgentConfig() config.AgentConfig {
	return embeddedAgentConfig
}
